 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: mqthiago/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: mqthiago
            # Text on contribution graph 
            text: THIAGO
       - uses: mqthiago/simple-push-action@v1
